### ISSUE TITLE
undefined: "github.com/gin-contrib/sessions".NewCookieStore

### ISSUE THREAD

**Issue by fanziyong** [angao/gin-xorm-admin#4]
router.init中报错，这个是什么意思，怎么解决。我的go版本本是1.11.5

**Comment by angao** [comment]
> router.init中报错，这个是什么意思，怎么解决。我的go版本本是1.11.5

你本地没有安装 github.com/gin-contrib/sessions 这个依赖吧

**Comment by fanziyong** [comment]
有呀，执行了go get github.com/gin-contrib/sessions，GOPATH里能看到gin-contrib/sessions这个包。

**Comment by angao** [comment]
这个问题是这个方法被移除了，你看下这个 [PR](https://github.com/angao/gin-xorm-admin/pull/5)，我重新实现了这个方法，你 rebase 下就可以了
